---
kind: pipeline
type: docker
name: kitchen's terraform

platform:
  os: linux
  arch: arm64

steps:
  - name: gcp central terraform
    image: alpine
    commands:
      - pwd
      - ls
      - env
      
      


    
  
