#cloud-config

write_files:
  - path: /etc/vault.hcl
    content: |
      listener "tcp" {
        tls_disable = true
        address = "0.0.0.0:8200"
      }

      seal "gcpckms" {
        project = "ssh-ca-vault"
        region = "us-central1"
        key_ring = "vault"
        crypto_key = "vault_seal"
      }

      storage "gcs" {
        bucket = "ssh-ca-vault"
      }

      ui = true
    permissions: 0644

packages:
  - vim
  - docker.io
  - curl

runcmd:
  - docker run -d -v /etc/vault.hcl:/vault/config/vault.hcl -p 80:8200/tcp --name vault vault
